FROM node:20-alpine AS build

# Define build arguments for environment variables
ARG VITE_BACKEND_URL
ARG VITE_FRONTEND_URL
ARG VITE_GLOBAL_WEBSOCKET_URL

# Set environment variables during the build process
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_GLOBAL_WEBSOCKET_URL=$VITE_GLOBAL_WEBSOCKET_URL


WORKDIR /app
COPY package.json .
RUN npm install
# COPY . .
EXPOSE 5173


# CMD [ "npm", "run", "dev" ]
CMD ["tail", "-f", "/dev/null"]