services:
  # devcontainer_backend:
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/devcontainer_backend/Dockerfile
  #   container_name: devcontainer_backend
  #   command: /bin/sh -c "while sleep 1000; do :; done"
  #   volumes:
  #     - .:/workspace:cached
  #   # working_dir: /backend
  #   depends_on:
  #     - backend

  devcontainer_backend:
    image: mcr.microsoft.com/vscode/devcontainers/python:3
    container_name: devcontainer_backend
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
    links:
      - devcontainer_frontend

  devcontainer_frontend:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18
    container_name: devcontainer_frontend
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

