services:

  backend:
    build: ./transcendence_backend
    container_name: backend
    env_file: '.env'
    volumes:
      - backend_data:/app/
      - staticfiles:/app/static/
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - staticfiles:/app/static/
      - ./transcendence_frontend/dist:/var/www/pong_spa
      - ./nginx/nginx.conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/pong42.com:/etc/nginx/ssl/pong
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: '.env'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file: '.env'
    volumes:
      - pgadmin-data:/var/lib/pgadmin



volumes:
  backend_data:
    name: backend_data
    driver: local
    driver_opts:
      device: ./transcendence_backend/backend
      o: bind
      type: none

  postgres-data:

  pgadmin-data:
  
  staticfiles:
      name: staticfiles
      driver: local
      driver_opts:
        device: ./transcendence_backend/static
        o: bind
        type: none

# networks:
#   default:
#     name: main_network