# Generated by Django 5.0.4 on 2024-04-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_profile',
            field=models.BooleanField(default=False),
        ),
    ]
