# Generated by Django 5.0.3 on 2024-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='win_loss_margin',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
