# Generated by Django 5.0.3 on 2024-07-30 15:13

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_player_win_loss_margin_player_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, default=user.models.set_default_avatar, max_length=255, null=True, upload_to=user.models.get_avatar_path),
        ),
    ]
