# Generated by Django 5.0.3 on 2024-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='online_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
