# Generated by Django 5.0.3 on 2024-08-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(choices=[(0, 'Pong'), (1, 'Other')], null=True)),
                ('game_mode', models.CharField(max_length=20, null=True)),
                ('round', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('scheduled', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to='user.player')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='user.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_score', models.IntegerField()),
                ('player_two_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
                ('game_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_id', to='game.gameschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament', max_length=30)),
                ('game_id', models.IntegerField(choices=[(0, 'Pong'), (1, 'Other')], null=True)),
                ('mode', models.CharField(max_length=50)),
                ('nb_player', models.IntegerField(blank=True, null=True)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=20, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_creator', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='tournament_players', to='user.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_gs', to='game.tournament'),
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(choices=[(0, 'Pong'), (1, 'Other')], null=True)),
                ('game_mode', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_gr', to='game.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losers', models.ManyToManyField(related_name='losers', to='user.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_tl', to='game.tournament')),
                ('winners', models.ManyToManyField(related_name='winners', to='user.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=30)),
                ('xp', models.IntegerField(default=0)),
                ('round', models.PositiveIntegerField(default=0)),
                ('stage', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tournaments', to='user.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to='game.tournament')),
            ],
        ),
    ]
