# Generated by Django 5.0.3 on 2024-07-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('user', '0004_player_win_loss_margin_player_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentlobby',
            name='player_one',
        ),
        migrations.RemoveField(
            model_name='tournamentlobby',
            name='player_two',
        ),
        migrations.RemoveField(
            model_name='tournamentlobby',
            name='result',
        ),
        migrations.RemoveField(
            model_name='tournamentlobby',
            name='round',
        ),
        migrations.RemoveField(
            model_name='tournamentlobby',
            name='status',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournamentlobby',
            name='losers',
            field=models.ManyToManyField(related_name='losers', to='user.player'),
        ),
        migrations.AddField(
            model_name='tournamentlobby',
            name='winners',
            field=models.ManyToManyField(related_name='winners', to='user.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('num_round', models.IntegerField(default=0)),
                ('round', models.CharField(default='First Round', max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tournaments', to='user.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to='game.tournament')),
            ],
        ),
    ]
