# Generated by Django 5.0.3 on 2024-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_tournamentlobby_player_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='nb_rounds',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='num_round',
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
