# Generated by Django 5.0.3 on 2024-08-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_tournamentlobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='alias',
        ),
    ]
