# Generated by Django 5.0.3 on 2024-08-06 10:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatroom',
            managers=[
                ('rooms', django.db.models.manager.Manager()),
            ],
        ),
    ]
